services:
  supmeca-planning:
    build: .
    container_name: supmeca-planning
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    env_file:
      - .env
